"""CLI interface: detect, scan, report."""

from __future__ import annotations

from pathlib import Path

import sys

import click

from . import __version__
from .evolution import get_changed_files, get_evolog, get_file_content, get_recent_changes
from .functions import diff_functions, supported_extensions
from .output import format_json, format_table
from .score import SupersessionCandidate, filter_candidates, score_pair


def _analyze_chain(
    change_id: str, *, cwd: str | None = None, threshold: float = 0.5
) -> list[SupersessionCandidate]:
    """Analyze a single change's evolution for superseded functions."""
    chain = get_evolog(change_id, cwd=cwd)
    if len(chain.entries) < 2:
        return []

    exts = supported_extensions()
    all_candidates: list[SupersessionCandidate] = []

    for succ, pred in chain.pairs():
        # Skip snapshots — they're auto-generated by jj, not intentional rewrites
        if succ.is_snapshot and pred.is_snapshot:
            continue

        changed_files = get_changed_files(pred.commit_id, succ.commit_id, cwd=cwd)
        source_files = [f for f in changed_files if Path(f).suffix in exts]

        for path in source_files:
            old_src = get_file_content(pred.commit_id, path, cwd=cwd)
            new_src = get_file_content(succ.commit_id, path, cwd=cwd)
            diff = diff_functions(old_src, new_src, path)
            candidates = score_pair(pred, succ, diff)
            all_candidates.extend(candidates)

    return filter_candidates(all_candidates, threshold)


@click.group()
@click.version_option(__version__)
def main() -> None:
    """jj-supersede: detect function-level code supersession."""


@main.command()
@click.argument("change_id")
@click.option("--threshold", "-t", default=0.5, type=float, help="Minimum score threshold (0-1)")
@click.option("--json", "as_json", is_flag=True, help="Output as JSON")
@click.option("--cwd", "-C", default=None, type=click.Path(exists=True), help="Repository path")
def detect(change_id: str, threshold: float, as_json: bool, cwd: str | None) -> None:
    """Detect superseded functions in a change's evolution history."""
    candidates = _analyze_chain(change_id, cwd=cwd, threshold=threshold)
    if as_json:
        click.echo(format_json(candidates))
    else:
        click.echo(format_table(candidates))


@main.command()
@click.option("--threshold", "-t", default=0.5, type=float, help="Minimum score threshold (0-1)")
@click.option("--limit", "-n", default=20, type=int, help="Max changes to scan")
@click.option("--revset", "-r", default="mutable()", help="Revset to scan")
@click.option("--json", "as_json", is_flag=True, help="Output as JSON")
@click.option("--cwd", "-C", default=None, type=click.Path(exists=True), help="Repository path")
def scan(threshold: float, limit: int, revset: str, as_json: bool, cwd: str | None) -> None:
    """Scan recent changes for superseded functions."""
    change_ids = get_recent_changes(cwd=cwd, limit=limit, revset=revset)
    all_candidates: list[SupersessionCandidate] = []
    errors = 0

    for cid in change_ids:
        try:
            candidates = _analyze_chain(cid, cwd=cwd, threshold=threshold)
            all_candidates.extend(candidates)
        except RuntimeError as e:
            errors += 1
            click.echo(f"warning: skipped {cid[:12]}: {e}", err=True)

    if errors:
        click.echo(f"warning: {errors}/{len(change_ids)} changes failed to analyze", err=True)

    deduped = filter_candidates(all_candidates, threshold)
    if as_json:
        click.echo(format_json(deduped))
    else:
        click.echo(format_table(deduped))


@main.command()
@click.option("--threshold", "-t", default=0.5, type=float, help="Minimum score threshold (0-1)")
@click.option("--limit", "-n", default=20, type=int, help="Max changes to scan")
@click.option("--revset", "-r", default="mutable()", help="Revset to scan")
@click.option("--cwd", "-C", default=None, type=click.Path(exists=True), help="Repository path")
def report(threshold: float, limit: int, revset: str, cwd: str | None) -> None:
    """Generate JSON report for signum integration."""
    change_ids = get_recent_changes(cwd=cwd, limit=limit, revset=revset)
    all_candidates: list[SupersessionCandidate] = []
    errors = 0

    for cid in change_ids:
        try:
            candidates = _analyze_chain(cid, cwd=cwd, threshold=threshold)
            all_candidates.extend(candidates)
        except RuntimeError as e:
            errors += 1
            click.echo(f"warning: skipped {cid[:12]}: {e}", err=True)

    if errors:
        click.echo(f"warning: {errors}/{len(change_ids)} changes failed to analyze", err=True)

    deduped = filter_candidates(all_candidates, threshold)
    click.echo(format_json(deduped))
